services:
  - type: web
    name: shift-app-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_PATH
        value: /var/data/app.db
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
